//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieClub.MovieDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBMovie
    {
        public DBMovie()
        {
            this.DBFavorites = new HashSet<DBFavorite>();
            this.DBFeatureds = new HashSet<DBFeatured>();
            this.DBMovieToCategories = new HashSet<DBMovieToCategory>();
            this.DBPaymentsDues = new HashSet<DBPaymentsDue>();
            this.DBRatings = new HashSet<DBRating>();
            this.DBRecommendations = new HashSet<DBRecommendation>();
            this.DBRents = new HashSet<DBRent>();
            this.DBReservations = new HashSet<DBReservation>();
            this.DBWatchLists = new HashSet<DBWatchList>();
        }
    
        public int Id { get; set; }
        public string ImdbId { get; set; }
        public string Name { get; set; }
        public string Year { get; set; }
        public string ReleaseDate { get; set; }
        public int Runtime { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        public string Actors { get; set; }
        public string Writer { get; set; }
        public string PlotShort { get; set; }
        public string PlotFull { get; set; }
        public string Language { get; set; }
        public string Country { get; set; }
        public string Awards { get; set; }
        public string PosterURL { get; set; }
        public double ImdbRatings { get; set; }
        public long ImdbVotes { get; set; }
        public double MovieClubRatings { get; set; }
        public int MovieClubRentCount { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public int Views { get; set; }
        public string TrailerURL { get; set; }
        public int MovieClubVotes { get; set; }
    
        public virtual ICollection<DBFavorite> DBFavorites { get; set; }
        public virtual ICollection<DBFeatured> DBFeatureds { get; set; }
        public virtual DBMovie DBMovies1 { get; set; }
        public virtual DBMovie DBMovy1 { get; set; }
        public virtual ICollection<DBMovieToCategory> DBMovieToCategories { get; set; }
        public virtual ICollection<DBPaymentsDue> DBPaymentsDues { get; set; }
        public virtual ICollection<DBRating> DBRatings { get; set; }
        public virtual ICollection<DBRecommendation> DBRecommendations { get; set; }
        public virtual ICollection<DBRent> DBRents { get; set; }
        public virtual ICollection<DBReservation> DBReservations { get; set; }
        public virtual ICollection<DBWatchList> DBWatchLists { get; set; }
    }
}
