//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieClub.MovieDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBReview
    {
        public int ReviewId { get; set; }
        public int MovieId { get; set; }
        public string Username { get; set; }
        public string Comment { get; set; }
    
        public virtual DBMovie DBMovy { get; set; }
    }
}
