//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieClub.MovieDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBUser
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> BorrowedCount { get; set; }
        public string PhotoURL { get; set; }
    }
}
